### ISSUE TITLE
Inaccurate root cause analysis

### ISSUE THREAD

**Issue by N00BIER** [Valentin-Metz/writeup_split#1]
You would be surprised but the crash occurs NOT in memcpy()...
```
in icalloc 
in xicalloc
in next_file_name  
in cwrite 
in line_bytes_split 
```

**Comment by Valentin-Metz** [comment]
Did you execute this with ASAN?
This is a heap metadata corruption, so anything that attempts to allocate or free memory can potentially crash, once the data has been overwritten.

**Comment by N00BIER** [comment]
> Did you execute this with ASAN? This is a heap metadata corruption, so anything that attempts to allocate or free memory can potentially crash, once the data has been overwritten.

Used gdb:

```
malloc(): corrupted top size

Program received signal SIGABRT, Aborted.
__pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
44	./nptl/pthread_kill.c: No such file or directory.
(gdb) bt
#0  __pthread_kill_implementation (no_tid=0, signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:44
#1  __pthread_kill_internal (signo=6, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#2  __GI___pthread_kill (threadid=<optimized out>, signo=signo@entry=6) at ./nptl/pthread_kill.c:89
#3  0x00007ffff7c3c3b6 in __GI_raise (sig=sig@entry=6) at ../sysdeps/posix/raise.c:26
#4  0x00007ffff7c2287c in __GI_abort () at ./stdlib/abort.c:79
#5  0x00007ffff7c235a4 in __libc_message (fmt=fmt@entry=0x7ffff7db890f "%s\n") at ../sysdeps/posix/libc_fatal.c:150
#6  0x00007ffff7c9b677 in malloc_printerr (str=str@entry=0x7ffff7db6457 "malloc(): corrupted top size") at ./malloc/malloc.c:5651
#7  0x00007ffff7c9ef5d in _int_malloc (av=av@entry=0x7ffff7df6c80 <main_arena>, bytes=bytes@entry=24) at ./malloc/malloc.c:4359
#8  0x00007ffff7ca0f61 in __libc_calloc (n=n@entry=3, elem_size=elem_size@entry=8) at ./malloc/malloc.c:3664
#9  0x000055555555d304 in icalloc (s=8, n=3) at lib/ialloc.h:81
#10 xicalloc (n=n@entry=3, s=s@entry=8) at lib/xmalloc.c:306
#11 0x0000555555558959 in next_file_name () at src/split.c:421
#12 0x0000555555559389 in cwrite (new_file_flag=<optimized out>, bp=bp@entry=0x555555566880 "|\001", bytes=bytes@entry=756) at src/split.c:628
#13 0x000055555555793c in line_bytes_split (bufsize=131072, buf=0x7ffff7f8c000 "", n_bytes=<optimized out>) at src/split.c:819
#14 main (argc=<optimized out>, argv=<optimized out>) at src/split.c:1689

```

**Comment by Valentin-Metz** [comment]
Without ASAN you won't get a precise location of where the bug originates from.
This specific input just _happens_ to crash here because that's where the heap data that got corrupted earlier gets used again for the first time.

**Comment by N00BIER** [comment]
Fair enough
